//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessWhoDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public int idMatch { get; set; }
        public Nullable<int> score { get; set; }
        public int idWinner { get; set; }
    
        public virtual User User { get; set; }
    }
}
