//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessWhoDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int idReport { get; set; }
        public string comment { get; set; }
        public Nullable<int> idReportedUser { get; set; }
        public Nullable<int> idReportType { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
    
        public virtual User User { get; set; }
        public virtual ReportType ReportType { get; set; }
    }
}
