//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessWhoDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int idUser { get; set; }
        public string nickname { get; set; }
        public string fullName { get; set; }
        public byte[] avatar { get; set; }
        public int idAccount { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
