//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessWhoClient.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GuessWhoClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Amigo.
        /// </summary>
        public static string btnAddFriend {
            get {
                return ResourceManager.GetString("btnAddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver al menú.
        /// </summary>
        public static string btnBackToMenu {
            get {
                return ResourceManager.GetString("btnBackToMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar partida.
        /// </summary>
        public static string btnCancelGame {
            get {
                return ResourceManager.GetString("btnCancelGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar adivinado.
        /// </summary>
        public static string btnCancelGuess {
            get {
                return ResourceManager.GetString("btnCancelGuess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string btnCancelReport {
            get {
                return ResourceManager.GetString("btnCancelReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar contraseña.
        /// </summary>
        public static string btnChangePassword {
            get {
                return ResourceManager.GetString("btnChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        public static string btnConfirmCode {
            get {
                return ResourceManager.GetString("btnConfirmCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continuar.
        /// </summary>
        public static string btnContinueAfterReport {
            get {
                return ResourceManager.GetString("btnContinueAfterReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Cuenta.
        /// </summary>
        public static string btnCreateAccount {
            get {
                return ResourceManager.GetString("btnCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitar por correo.
        /// </summary>
        public static string btnEmailInvitation {
            get {
                return ResourceManager.GetString("btnEmailInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Terminar intento.
        /// </summary>
        public static string btnFinishAttempt {
            get {
                return ResourceManager.GetString("btnFinishAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AMIGOS.
        /// </summary>
        public static string btnFriends {
            get {
                return ResourceManager.GetString("btnFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comenzar partida.
        /// </summary>
        public static string btnGoToGame {
            get {
                return ResourceManager.GetString("btnGoToGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adivinar.
        /// </summary>
        public static string btnGuess {
            get {
                return ResourceManager.GetString("btnGuess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de invitación.
        /// </summary>
        public static string btnInvitationCode {
            get {
                return ResourceManager.GetString("btnInvitationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse a partida.
        /// </summary>
        public static string btnJoinMatch {
            get {
                return ResourceManager.GetString("btnJoinMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MARCADOR.
        /// </summary>
        public static string btnLeaderboard {
            get {
                return ResourceManager.GetString("btnLeaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abandonar.
        /// </summary>
        public static string btnLeave {
            get {
                return ResourceManager.GetString("btnLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string btnLeaveGame {
            get {
                return ResourceManager.GetString("btnLeaveGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SALIR.
        /// </summary>
        public static string btnLogOut {
            get {
                return ResourceManager.GetString("btnLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PARTIDA RÁPIDA.
        /// </summary>
        public static string btnQuickMatch {
            get {
                return ResourceManager.GetString("btnQuickMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportar jugador.
        /// </summary>
        public static string btnReportPlayer {
            get {
                return ResourceManager.GetString("btnReportPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comenzar juego.
        /// </summary>
        public static string btnStartGame {
            get {
                return ResourceManager.GetString("btnStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CAMPEONATO.
        /// </summary>
        public static string btnTournamentMatch {
            get {
                return ResourceManager.GetString("btnTournamentMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar imagen.
        /// </summary>
        public static string btnUploadImage {
            get {
                return ResourceManager.GetString("btnUploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargar foto de perfil.
        /// </summary>
        public static string btnUploadProfilePicture {
            get {
                return ResourceManager.GetString("btnUploadProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string cbLanguageOptionTwo {
            get {
                return ResourceManager.GetString("cbLanguageOptionTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugador que realiza trampas.
        /// </summary>
        public static string cbReportReasonOptionOne {
            get {
                return ResourceManager.GetString("cbReportReasonOptionOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dibujo fuera de contexto.
        /// </summary>
        public static string cbReportReasonOptionThree {
            get {
                return ResourceManager.GetString("cbReportReasonOptionThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Antideportividad.
        /// </summary>
        public static string cbReportReasonOptionTwo {
            get {
                return ResourceManager.GetString("cbReportReasonOptionTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione una opción.
        /// </summary>
        public static string cbReportReasonPlaceholder {
            get {
                return ResourceManager.GetString("cbReportReasonPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿No tienes cuenta?.
        /// </summary>
        public static string lbAccountQuestion {
            get {
                return ResourceManager.GetString("lbAccountQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio de Contraseña.
        /// </summary>
        public static string lbChangePassword {
            get {
                return ResourceManager.GetString("lbChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Se parece a tu personaje?.
        /// </summary>
        public static string lbCharacterLooksLikeQuestion {
            get {
                return ResourceManager.GetString("lbCharacterLooksLikeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Escoge tu personaje!.
        /// </summary>
        public static string lbChooseCharacter {
            get {
                return ResourceManager.GetString("lbChooseCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hemos enviado un código de verificación al correo que nos has proporcionado, por favor colócalo debajo para concluir con la creación de tu cuenta..
        /// </summary>
        public static string lbConfirmAccountDescription {
            get {
                return ResourceManager.GetString("lbConfirmAccountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de Confirmación.
        /// </summary>
        public static string lbConfirmationCode {
            get {
                return ResourceManager.GetString("lbConfirmationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirme su contraseña.
        /// </summary>
        public static string lbConfirmPassword {
            get {
                return ResourceManager.GetString("lbConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string lbEmailGlobal {
            get {
                return ResourceManager.GetString("lbEmailGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amigos conectados.
        /// </summary>
        public static string lbFriendsConnected {
            get {
                return ResourceManager.GetString("lbFriendsConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre completo.
        /// </summary>
        public static string lbFullName {
            get {
                return ResourceManager.GetString("lbFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string lbFullNameProfile {
            get {
                return ResourceManager.GetString("lbFullNameProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Dibuja! A diferencia del juego original, aquí no podrás hacer preguntas a tu contrincante, en su lugar, deberás usar tu imaginación y realizar un dibujo para transmitir tu pregunta. Una vez terminado tu dibujo, termina tu intento y ve al siguiente paso..
        /// </summary>
        public static string lbHowToPlayDescription {
            get {
                return ResourceManager.GetString("lbHowToPlayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desconectados.
        /// </summary>
        public static string lbOfflineFriends {
            get {
                return ResourceManager.GetString("lbOfflineFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conectados.
        /// </summary>
        public static string lbOnlineFriends {
            get {
                return ResourceManager.GetString("lbOnlineFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string lbPasswordGlobal {
            get {
                return ResourceManager.GetString("lbPasswordGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Posición.
        /// </summary>
        public static string lbRankHeaderRow {
            get {
                return ResourceManager.GetString("lbRankHeaderRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repite tu Contraseña.
        /// </summary>
        public static string lbRepeatPassword {
            get {
                return ResourceManager.GetString("lbRepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentario.
        /// </summary>
        public static string lbReportComment {
            get {
                return ResourceManager.GetString("lbReportComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No habrá ninguna penalización por finalizar la partida..
        /// </summary>
        public static string lbReportFinishedMessage {
            get {
                return ResourceManager.GetString("lbReportFinishedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Razón del reporte.
        /// </summary>
        public static string lbReportReason {
            get {
                return ResourceManager.GetString("lbReportReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntuación.
        /// </summary>
        public static string lbScoreHeaderRow {
            get {
                return ResourceManager.GetString("lbScoreHeaderRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Ups! No se ha encontrado ningún usuario con ese nombre.
        /// </summary>
        public static string lbStatusRequestFailed {
            get {
                return ResourceManager.GetString("lbStatusRequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Se ha enviado la solicitud correctamente! .
        /// </summary>
        public static string lbStatusRequestSuccess {
            get {
                return ResourceManager.GetString("lbStatusRequestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar Cuenta.
        /// </summary>
        public static string lbTitleConfirmAccount {
            get {
                return ResourceManager.GetString("lbTitleConfirmAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis Amigos.
        /// </summary>
        public static string lbTitleFriends {
            get {
                return ResourceManager.GetString("lbTitleFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Cómo jugar?.
        /// </summary>
        public static string lbTitleHowToPlay {
            get {
                return ResourceManager.GetString("lbTitleHowToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marcador Global.
        /// </summary>
        public static string lbTitleLeaderboard {
            get {
                return ResourceManager.GetString("lbTitleLeaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi perfil.
        /// </summary>
        public static string lbTitleMyProfile {
            get {
                return ResourceManager.GetString("lbTitleMyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador ha sido reportado, ¿Deseas terminar la partida?.
        /// </summary>
        public static string lbTitleReportFinished {
            get {
                return ResourceManager.GetString("lbTitleReportFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esperando oponente….
        /// </summary>
        public static string lbWaitingOpponent {
            get {
                return ResourceManager.GetString("lbWaitingOpponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esperando jugador….
        /// </summary>
        public static string lbWaitingPlayer {
            get {
                return ResourceManager.GetString("lbWaitingPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por el momento no hay conexión, por favor intentélo más tarde.
        /// </summary>
        public static string msgbConectionLost {
            get {
                return ResourceManager.GetString("msgbConectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al enviar el correo electrónico, intente registrarse en otro momento.
        /// </summary>
        public static string msgbConfirmEmailSendingErrorMessage {
            get {
                return ResourceManager.GetString("msgbConfirmEmailSendingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de envío.
        /// </summary>
        public static string msgbConfirmEmailSendingErrorTitle {
            get {
                return ResourceManager.GetString("msgbConfirmEmailSendingErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico y la contraseña son requeridos.
        /// </summary>
        public static string msgbEmptyField {
            get {
                return ResourceManager.GetString("msgbEmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La imagen debe tener un tamaño de 20kb o menos..
        /// </summary>
        public static string msgbRegisterAlertImageSizeMessage {
            get {
                return ResourceManager.GetString("msgbRegisterAlertImageSizeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño de imagen excedido.
        /// </summary>
        public static string msgbRegisterAlertImageSizeTitle {
            get {
                return ResourceManager.GetString("msgbRegisterAlertImageSizeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese información en cada uno de los campos para poder continuar.
        /// </summary>
        public static string msgbRegisterEmptyFieldsMessage {
            get {
                return ResourceManager.GetString("msgbRegisterEmptyFieldsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campos vacíos.
        /// </summary>
        public static string msgbRegisterEmptyFieldsTitle {
            get {
                return ResourceManager.GetString("msgbRegisterEmptyFieldsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al tratar de recuperar la imagen, intente nuevamente.
        /// </summary>
        public static string msgbRegisterImageNotFoundMessage {
            get {
                return ResourceManager.GetString("msgbRegisterImageNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen no encontrada.
        /// </summary>
        public static string msgbRegisterImageNotFoundTitle {
            get {
                return ResourceManager.GetString("msgbRegisterImageNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe tener mínimo 8 caracteres y, al menos, una letra minúscula, una letra mayúscula, un número y un caracter especial (¡, @, -, $, #, %, _, etc.)..
        /// </summary>
        public static string msgbRegisterInsecurePasswordMessage {
            get {
                return ResourceManager.GetString("msgbRegisterInsecurePasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseñas insegura.
        /// </summary>
        public static string msgbRegisterInsecurePasswordTitle {
            get {
                return ResourceManager.GetString("msgbRegisterInsecurePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Corrija el correo electrónico a un formato válido.
        /// </summary>
        public static string msgbRegisterInvalidEmailMessage {
            get {
                return ResourceManager.GetString("msgbRegisterInvalidEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico inválido.
        /// </summary>
        public static string msgbRegisterInvalidEmailTitle {
            get {
                return ResourceManager.GetString("msgbRegisterInvalidEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario solo debe conetener letras, números y guiones bajos.
        /// </summary>
        public static string msgbRegisterInvalidNicknameMessage {
            get {
                return ResourceManager.GetString("msgbRegisterInvalidNicknameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario inválido.
        /// </summary>
        public static string msgbRegisterInvalidNicknameTitle {
            get {
                return ResourceManager.GetString("msgbRegisterInvalidNicknameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas ingresadas no coinciden, modifique los campos para que lo hagan.
        /// </summary>
        public static string msgbRegisterMismatchPasswordMessage {
            get {
                return ResourceManager.GetString("msgbRegisterMismatchPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseñas no coincidentes.
        /// </summary>
        public static string msgbRegisterMismatchPasswordTitle {
            get {
                return ResourceManager.GetString("msgbRegisterMismatchPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe una cuenta registrada con ese correo electrónico, intente con otro.
        /// </summary>
        public static string msgbRegisterRegisteredEmailMessage {
            get {
                return ResourceManager.GetString("msgbRegisterRegisteredEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico registrado.
        /// </summary>
        public static string msgbRegisterRegisteredEmailTitle {
            get {
                return ResourceManager.GetString("msgbRegisterRegisteredEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe otro jugador utilizando el nombre de usuario ingresado, intente con otro.
        /// </summary>
        public static string msgbRegisterRegisteredNicknameMessage {
            get {
                return ResourceManager.GetString("msgbRegisterRegisteredNicknameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario registrado.
        /// </summary>
        public static string msgbRegisterRegisteredNicknameTitle {
            get {
                return ResourceManager.GetString("msgbRegisterRegisteredNicknameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo y/o contraseña son incorrectas, por favor verifique la información.
        /// </summary>
        public static string msgbUserNotFound {
            get {
                return ResourceManager.GetString("msgbUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido/a .
        /// </summary>
        public static string msgbWelcome1 {
            get {
                return ResourceManager.GetString("msgbWelcome1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  a Adivina Quién.
        /// </summary>
        public static string msgbWelcome2 {
            get {
                return ResourceManager.GetString("msgbWelcome2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código introducido no coincide con el código generado.
        /// </summary>
        public static string msgbWrongConfirmationCodeMessage {
            get {
                return ResourceManager.GetString("msgbWrongConfirmationCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verifique el código ingresado.
        /// </summary>
        public static string msgbWrongConfirmationCodeTitle {
            get {
                return ResourceManager.GetString("msgbWrongConfirmationCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string tbCodePlaceholder {
            get {
                return ResourceManager.GetString("tbCodePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Explica la situación.
        /// </summary>
        public static string tbReportCommentPlaceholder {
            get {
                return ResourceManager.GetString("tbReportCommentPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe un mensaje….
        /// </summary>
        public static string tbSendMessagePlaceholder {
            get {
                return ResourceManager.GetString("tbSendMessagePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu código de confirmación.
        /// </summary>
        public static string txtConfirmationEmailBody {
            get {
                return ResourceManager.GetString("txtConfirmationEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmación de correo electrónico.
        /// </summary>
        public static string txtConfirmationEmailSubject {
            get {
                return ResourceManager.GetString("txtConfirmationEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marcador.
        /// </summary>
        public static string txtLeaderboardGlobal {
            get {
                return ResourceManager.GetString("txtLeaderboardGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        public static string txtLoginGlobal {
            get {
                return ResourceManager.GetString("txtLoginGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú Principal.
        /// </summary>
        public static string txtMainMenuTitle {
            get {
                return ResourceManager.GetString("txtMainMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario.
        /// </summary>
        public static string txtNicknameGlobal {
            get {
                return ResourceManager.GetString("txtNicknameGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportar.
        /// </summary>
        public static string txtReportGlobal {
            get {
                return ResourceManager.GetString("txtReportGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regístrate.
        /// </summary>
        public static string txtSignUpGlobal {
            get {
                return ResourceManager.GetString("txtSignUpGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error de conexión y la aplicación no pudo completar la solicitud, intente más tarde..
        /// </summary>
        public static string txtSQLErrorMessage {
            get {
                return ResourceManager.GetString("txtSQLErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de conexión.
        /// </summary>
        public static string txtSQLErrorTitle {
            get {
                return ResourceManager.GetString("txtSQLErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La aplicación no logó completar la solicitud, por favor reporte el error e intente más tarde..
        /// </summary>
        public static string txtUpdateErrorMessage {
            get {
                return ResourceManager.GetString("txtUpdateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de actualización.
        /// </summary>
        public static string txtUpdateErrorTitle {
            get {
                return ResourceManager.GetString("txtUpdateErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La aplicación no logró completar la solicitud debido a un error en el formato de los datos, por favor reporte el error..
        /// </summary>
        public static string txtValidationErrorMessage {
            get {
                return ResourceManager.GetString("txtValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos inválidos.
        /// </summary>
        public static string txtValidationErrorTitle {
            get {
                return ResourceManager.GetString("txtValidationErrorTitle", resourceCulture);
            }
        }
    }
}
