//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessWhoClient.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GuessWhoClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Amigo.
        /// </summary>
        public static string btnAddFriend {
            get {
                return ResourceManager.GetString("btnAddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VOLVER AL MENÚ.
        /// </summary>
        public static string btnBackToMenu {
            get {
                return ResourceManager.GetString("btnBackToMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar partida.
        /// </summary>
        public static string btnCancelGame {
            get {
                return ResourceManager.GetString("btnCancelGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar adivinado.
        /// </summary>
        public static string btnCancelGuess {
            get {
                return ResourceManager.GetString("btnCancelGuess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string btnCancelReport {
            get {
                return ResourceManager.GetString("btnCancelReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar contraseña.
        /// </summary>
        public static string btnChangePassword {
            get {
                return ResourceManager.GetString("btnChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar Selección.
        /// </summary>
        public static string btnConfirmCharacterSelection {
            get {
                return ResourceManager.GetString("btnConfirmCharacterSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar.
        /// </summary>
        public static string btnConfirmCode {
            get {
                return ResourceManager.GetString("btnConfirmCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continuar.
        /// </summary>
        public static string btnContinueAfterReport {
            get {
                return ResourceManager.GetString("btnContinueAfterReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Cuenta.
        /// </summary>
        public static string btnCreateAccount {
            get {
                return ResourceManager.GetString("btnCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitar por correo.
        /// </summary>
        public static string btnEmailInvitation {
            get {
                return ResourceManager.GetString("btnEmailInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abandonar partida.
        /// </summary>
        public static string btnExitGame {
            get {
                return ResourceManager.GetString("btnExitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Terminar intento.
        /// </summary>
        public static string btnFinishAttempt {
            get {
                return ResourceManager.GetString("btnFinishAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AMIGOS.
        /// </summary>
        public static string btnFriends {
            get {
                return ResourceManager.GetString("btnFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comenzar partida.
        /// </summary>
        public static string btnGoToGame {
            get {
                return ResourceManager.GetString("btnGoToGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adivinar.
        /// </summary>
        public static string btnGuess {
            get {
                return ResourceManager.GetString("btnGuess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de invitación.
        /// </summary>
        public static string btnInvitationCode {
            get {
                return ResourceManager.GetString("btnInvitationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse a partida.
        /// </summary>
        public static string btnJoinMatch {
            get {
                return ResourceManager.GetString("btnJoinMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MARCADOR.
        /// </summary>
        public static string btnLeaderboard {
            get {
                return ResourceManager.GetString("btnLeaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abandonar.
        /// </summary>
        public static string btnLeave {
            get {
                return ResourceManager.GetString("btnLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string btnLeaveGame {
            get {
                return ResourceManager.GetString("btnLeaveGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SALIR.
        /// </summary>
        public static string btnLogOut {
            get {
                return ResourceManager.GetString("btnLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PARTIDA RÁPIDA.
        /// </summary>
        public static string btnQuickMatch {
            get {
                return ResourceManager.GetString("btnQuickMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comenzar juego.
        /// </summary>
        public static string btnStartGame {
            get {
                return ResourceManager.GetString("btnStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CAMPEONATO.
        /// </summary>
        public static string btnTournamentMatch {
            get {
                return ResourceManager.GetString("btnTournamentMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar imagen.
        /// </summary>
        public static string btnUploadImage {
            get {
                return ResourceManager.GetString("btnUploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargar foto de perfil.
        /// </summary>
        public static string btnUploadProfilePicture {
            get {
                return ResourceManager.GetString("btnUploadProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string cbLanguageOptionTwo {
            get {
                return ResourceManager.GetString("cbLanguageOptionTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugador que realiza trampas.
        /// </summary>
        public static string cbReportReasonOptionOne {
            get {
                return ResourceManager.GetString("cbReportReasonOptionOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dibujo fuera de contexto.
        /// </summary>
        public static string cbReportReasonOptionThree {
            get {
                return ResourceManager.GetString("cbReportReasonOptionThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Antideportividad.
        /// </summary>
        public static string cbReportReasonOptionTwo {
            get {
                return ResourceManager.GetString("cbReportReasonOptionTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione una opción.
        /// </summary>
        public static string cbReportReasonPlaceholder {
            get {
                return ResourceManager.GetString("cbReportReasonPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿No tienes cuenta?.
        /// </summary>
        public static string lbAccountQuestion {
            get {
                return ResourceManager.GetString("lbAccountQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡La partida está llena y lista para comenzar!.
        /// </summary>
        public static string lbAllPlayersReady {
            get {
                return ResourceManager.GetString("lbAllPlayersReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Auch!.
        /// </summary>
        public static string lbAuch {
            get {
                return ResourceManager.GetString("lbAuch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio de Contraseña.
        /// </summary>
        public static string lbChangePassword {
            get {
                return ResourceManager.GetString("lbChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Se parece a tu personaje?.
        /// </summary>
        public static string lbCharacterLooksLikeQuestion {
            get {
                return ResourceManager.GetString("lbCharacterLooksLikeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Escoge tu personaje!.
        /// </summary>
        public static string lbChooseCharacter {
            get {
                return ResourceManager.GetString("lbChooseCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu dibujo se parece al dibujo de tu oponente.
        /// </summary>
        public static string lbClueCorrectDraw {
            get {
                return ResourceManager.GetString("lbClueCorrectDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu dibujo NO se parece al de tu contrincante.
        /// </summary>
        public static string lbClueWrongDraw {
            get {
                return ResourceManager.GetString("lbClueWrongDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hemos enviado un código de verificación al correo que nos has proporcionado, por favor colócalo debajo para concluir con la creación de tu cuenta..
        /// </summary>
        public static string lbConfirmAccountDescription {
            get {
                return ResourceManager.GetString("lbConfirmAccountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de Confirmación.
        /// </summary>
        public static string lbConfirmationCode {
            get {
                return ResourceManager.GetString("lbConfirmationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirme su contraseña.
        /// </summary>
        public static string lbConfirmPassword {
            get {
                return ResourceManager.GetString("lbConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string lbEmailGlobal {
            get {
                return ResourceManager.GetString("lbEmailGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay jugadores por mostrar.
        /// </summary>
        public static string lbEmptyScoreboard {
            get {
                return ResourceManager.GetString("lbEmptyScoreboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre completo.
        /// </summary>
        public static string lbFullName {
            get {
                return ResourceManager.GetString("lbFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string lbFullNameProfile {
            get {
                return ResourceManager.GetString("lbFullNameProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Dibuja! A diferencia del juego original, aquí no podrás hacer preguntas a tu contrincante, en su lugar, deberás usar tu imaginación y realizar un dibujo para transmitir tu pregunta. Una vez terminado tu dibujo, termina tu intento y ve al siguiente paso..
        /// </summary>
        public static string lbHowToPlayDescription {
            get {
                return ResourceManager.GetString("lbHowToPlayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitar jugador.
        /// </summary>
        public static string lbInvitePlayer {
            get {
                return ResourceManager.GetString("lbInvitePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay jugadores activos por mostrar.
        /// </summary>
        public static string lbNoPlayersOnline {
            get {
                return ResourceManager.GetString("lbNoPlayersOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string lbPasswordGlobal {
            get {
                return ResourceManager.GetString("lbPasswordGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Posición.
        /// </summary>
        public static string lbRankHeaderRow {
            get {
                return ResourceManager.GetString("lbRankHeaderRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repite tu Contraseña.
        /// </summary>
        public static string lbRepeatPassword {
            get {
                return ResourceManager.GetString("lbRepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comentario.
        /// </summary>
        public static string lbReportComment {
            get {
                return ResourceManager.GetString("lbReportComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No habrá ninguna penalización por finalizar la partida..
        /// </summary>
        public static string lbReportFinishedMessage {
            get {
                return ResourceManager.GetString("lbReportFinishedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Razón del reporte.
        /// </summary>
        public static string lbReportReason {
            get {
                return ResourceManager.GetString("lbReportReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntuación.
        /// </summary>
        public static string lbScoreHeaderRow {
            get {
                return ResourceManager.GetString("lbScoreHeaderRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Ups! No se ha encontrado ningún usuario con ese nombre.
        /// </summary>
        public static string lbStatusRequestFailed {
            get {
                return ResourceManager.GetString("lbStatusRequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Se ha enviado la solicitud correctamente! .
        /// </summary>
        public static string lbStatusRequestSuccess {
            get {
                return ResourceManager.GetString("lbStatusRequestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar Cuenta.
        /// </summary>
        public static string lbTitleConfirmAccount {
            get {
                return ResourceManager.GetString("lbTitleConfirmAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis Amigos.
        /// </summary>
        public static string lbTitleFriends {
            get {
                return ResourceManager.GetString("lbTitleFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Cómo jugar?.
        /// </summary>
        public static string lbTitleHowToPlay {
            get {
                return ResourceManager.GetString("lbTitleHowToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marcador Global.
        /// </summary>
        public static string lbTitleLeaderboard {
            get {
                return ResourceManager.GetString("lbTitleLeaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi perfil.
        /// </summary>
        public static string lbTitleMyProfile {
            get {
                return ResourceManager.GetString("lbTitleMyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador ha sido reportado, ¿Deseas terminar la partida?.
        /// </summary>
        public static string lbTitleReportFinished {
            get {
                return ResourceManager.GetString("lbTitleReportFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espere, en breve comenzará la partida.
        /// </summary>
        public static string lbWaitGameToStart {
            get {
                return ResourceManager.GetString("lbWaitGameToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esperando oponente….
        /// </summary>
        public static string lbWaitingOpponent {
            get {
                return ResourceManager.GetString("lbWaitingOpponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esperando respuesta del contrincante.
        /// </summary>
        public static string lbWaitingOpponentAnswer {
            get {
                return ResourceManager.GetString("lbWaitingOpponentAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Bien hecho!.
        /// </summary>
        public static string lbWellDone {
            get {
                return ResourceManager.GetString("lbWellDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El otro jugador ha abandonado la partida, la partida ha sido cancelada.
        /// </summary>
        public static string msgbCanceledMatchMessage {
            get {
                return ResourceManager.GetString("msgbCanceledMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por el momento no hay conexión, por favor intentélo más tarde.
        /// </summary>
        public static string msgbConectionLost {
            get {
                return ResourceManager.GetString("msgbConectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al enviar el correo electrónico, intente registrarse en otro momento.
        /// </summary>
        public static string msgbConfirmEmailSendingErrorMessage {
            get {
                return ResourceManager.GetString("msgbConfirmEmailSendingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de envío.
        /// </summary>
        public static string msgbConfirmEmailSendingErrorTitle {
            get {
                return ResourceManager.GetString("msgbConfirmEmailSendingErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Dese elegir este personaje?.
        /// </summary>
        public static string msgbConfirmGuessChoiceMessage {
            get {
                return ResourceManager.GetString("msgbConfirmGuessChoiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirme su elección.
        /// </summary>
        public static string msgbConfirmGuessChoiceTitle {
            get {
                return ResourceManager.GetString("msgbConfirmGuessChoiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro de que deseas salir de la partida?.
        /// </summary>
        public static string msgbConfirmLeaveGameMessage {
            get {
                return ResourceManager.GetString("msgbConfirmLeaveGameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abandonar Partida.
        /// </summary>
        public static string msgbConfirmLeaveGameTitle {
            get {
                return ResourceManager.GetString("msgbConfirmLeaveGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico y la contraseña son requeridos.
        /// </summary>
        public static string msgbEmptyFieldMessage {
            get {
                return ResourceManager.GetString("msgbEmptyFieldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campos faltantes.
        /// </summary>
        public static string msgbEmptyFieldTitle {
            get {
                return ResourceManager.GetString("msgbEmptyFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, explique la situación del reporte.
        /// </summary>
        public static string msgbEmptyReportComment {
            get {
                return ResourceManager.GetString("msgbEmptyReportComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, complete todos los campos correctamente.
        /// </summary>
        public static string msgbEmptyReportFields {
            get {
                return ResourceManager.GetString("msgbEmptyReportFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, seleccione la razón del reporte.
        /// </summary>
        public static string msgbEmptyReportReason {
            get {
                return ResourceManager.GetString("msgbEmptyReportReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible establecer una conexión con el servidor, intente en otro momento.
        /// </summary>
        public static string msgbErrorConexionServidorMessage {
            get {
                return ResourceManager.GetString("msgbErrorConexionServidorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de conexión con el servidor.
        /// </summary>
        public static string msgbErrorConexionServidorTitle {
            get {
                return ResourceManager.GetString("msgbErrorConexionServidorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al unirse a la partida.
        /// </summary>
        public static string msgbErrorJoiningMatchTitle {
            get {
                return ResourceManager.GetString("msgbErrorJoiningMatchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al abandonar la partida, intente nuevamente.
        /// </summary>
        public static string msgbErrorLeavingMatchTitle {
            get {
                return ResourceManager.GetString("msgbErrorLeavingMatchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta partida es de tipo Campeonato. Para poder unirte a partidas de este tipo debes iniciar sesión..
        /// </summary>
        public static string msgbErrorNotAllowedToJoinMatchMessage {
            get {
                return ResourceManager.GetString("msgbErrorNotAllowedToJoinMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes unirte a la partida.
        /// </summary>
        public static string msgbErrorNotAllowedToJoinMatchTitle {
            get {
                return ResourceManager.GetString("msgbErrorNotAllowedToJoinMatchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al intentar recuperar el correo electrónico del jugador, por lo que la invitación no pudo ser enviada.
        /// </summary>
        public static string msgbErrorRetrievingPlayerEmailMessage {
            get {
                return ResourceManager.GetString("msgbErrorRetrievingPlayerEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al recuperar el correo del jugador.
        /// </summary>
        public static string msgbErrorRetrievingPlayerEmailTitle {
            get {
                return ResourceManager.GetString("msgbErrorRetrievingPlayerEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible enviar el código de invitación de la partida al correo electrónico del jugador. Intente copiando y enviando directamente el código.
        /// </summary>
        public static string msgbErrorSendingGameInvitationMessage {
            get {
                return ResourceManager.GetString("msgbErrorSendingGameInvitationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al enviar la invitación.
        /// </summary>
        public static string msgbErrorSendingGameInvitationTitle {
            get {
                return ResourceManager.GetString("msgbErrorSendingGameInvitationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor intente en otro momento, pues ha ocurrido un error al verificar el estado de su cuenta.
        /// </summary>
        public static string msgbErrorVerifyingBanMessage {
            get {
                return ResourceManager.GetString("msgbErrorVerifyingBanMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No pudo completarse la verificación del estado de su cuenta.
        /// </summary>
        public static string msgbErrorVerifyingBanTitle {
            get {
                return ResourceManager.GetString("msgbErrorVerifyingBanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estas seguro que deseas terminar tu intento? No podrás adivinar o dibujar más..
        /// </summary>
        public static string msgbFinishDrawMessage {
            get {
                return ResourceManager.GetString("msgbFinishDrawMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Terminar intento.
        /// </summary>
        public static string msgbFinishDrawTitle {
            get {
                return ResourceManager.GetString("msgbFinishDrawTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El anfitrión ha finalizado la partida.
        /// </summary>
        public static string msgbGameFinishedByHostMessage {
            get {
                return ResourceManager.GetString("msgbGameFinishedByHostMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partida finalizada.
        /// </summary>
        public static string msgbGameFinishedByHostTitle {
            get {
                return ResourceManager.GetString("msgbGameFinishedByHostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La partida ha sido finalizada por el anfitrión, por lo que no es posible unirse.
        /// </summary>
        public static string msgbHostLeftMatchMessage {
            get {
                return ResourceManager.GetString("msgbHostLeftMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partida finalizada por el anfitrión.
        /// </summary>
        public static string msgbHostLeftMatchTitle {
            get {
                return ResourceManager.GetString("msgbHostLeftMatchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo y/o contraseña son incorrectas, por favor verifique la información.
        /// </summary>
        public static string msgbInvalidCredentialsMessage {
            get {
                return ResourceManager.GetString("msgbInvalidCredentialsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Credenciales inválidas.
        /// </summary>
        public static string msgbInvalidCredentialsTitle {
            get {
                return ResourceManager.GetString("msgbInvalidCredentialsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La partida a la que intenta acceder no pudo ser encontrada, o es posible que ya se encuentre llena.
        /// </summary>
        public static string msgbInvalidMatchCodeMessage {
            get {
                return ResourceManager.GetString("msgbInvalidMatchCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partida inválida.
        /// </summary>
        public static string msgbInvalidMatchCodeTitle {
            get {
                return ResourceManager.GetString("msgbInvalidMatchCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe una sesión activa para la cuenta con la que intenta ingresar.
        /// </summary>
        public static string msgbInvalidSessionMessage {
            get {
                return ResourceManager.GetString("msgbInvalidSessionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sesión inválida.
        /// </summary>
        public static string msgbInvalidSessionTitle {
            get {
                return ResourceManager.GetString("msgbInvalidSessionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador ha sido invitado a la partida exitosamente.
        /// </summary>
        public static string msgbInvitationSentMessage {
            get {
                return ResourceManager.GetString("msgbInvitationSentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitación enviada.
        /// </summary>
        public static string msgbInvitationSentTitle {
            get {
                return ResourceManager.GetString("msgbInvitationSentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No ha sido posible enviar el mensaje, pues el jugador ha abandonado la partida.
        /// </summary>
        public static string msgbMesageNotSentMessage {
            get {
                return ResourceManager.GetString("msgbMesageNotSentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo enviar el mensaje.
        /// </summary>
        public static string msgbMessageNotSentTitle {
            get {
                return ResourceManager.GetString("msgbMessageNotSentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Su cuenta ha sido bloqueada permanentemente. No tiene acceso al juego.
        /// </summary>
        public static string msgbPermanentBanMessage {
            get {
                return ResourceManager.GetString("msgbPermanentBanMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta bloqueada permanentemente.
        /// </summary>
        public static string msgbPermanentBanTitle {
            get {
                return ResourceManager.GetString("msgbPermanentBanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La imagen debe tener un tamaño de 20kb o menos..
        /// </summary>
        public static string msgbRegisterAlertImageSizeMessage {
            get {
                return ResourceManager.GetString("msgbRegisterAlertImageSizeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño de imagen excedido.
        /// </summary>
        public static string msgbRegisterAlertImageSizeTitle {
            get {
                return ResourceManager.GetString("msgbRegisterAlertImageSizeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese información en cada uno de los campos para poder continuar.
        /// </summary>
        public static string msgbRegisterEmptyFieldsMessage {
            get {
                return ResourceManager.GetString("msgbRegisterEmptyFieldsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campos vacíos.
        /// </summary>
        public static string msgbRegisterEmptyFieldsTitle {
            get {
                return ResourceManager.GetString("msgbRegisterEmptyFieldsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al tratar de recuperar la imagen, intente nuevamente.
        /// </summary>
        public static string msgbRegisterImageNotFoundMessage {
            get {
                return ResourceManager.GetString("msgbRegisterImageNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen no encontrada.
        /// </summary>
        public static string msgbRegisterImageNotFoundTitle {
            get {
                return ResourceManager.GetString("msgbRegisterImageNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe tener mínimo 8 caracteres y, al menos, una letra minúscula, una letra mayúscula, un número y un caracter especial (¡, @, -, $, #, %, _, etc.)..
        /// </summary>
        public static string msgbRegisterInsecurePasswordMessage {
            get {
                return ResourceManager.GetString("msgbRegisterInsecurePasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseñas insegura.
        /// </summary>
        public static string msgbRegisterInsecurePasswordTitle {
            get {
                return ResourceManager.GetString("msgbRegisterInsecurePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Corrija el correo electrónico a un formato válido.
        /// </summary>
        public static string msgbRegisterInvalidEmailMessage {
            get {
                return ResourceManager.GetString("msgbRegisterInvalidEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico inválido.
        /// </summary>
        public static string msgbRegisterInvalidEmailTitle {
            get {
                return ResourceManager.GetString("msgbRegisterInvalidEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario solo debe conetener letras, números y guiones bajos.
        /// </summary>
        public static string msgbRegisterInvalidNicknameMessage {
            get {
                return ResourceManager.GetString("msgbRegisterInvalidNicknameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario inválido.
        /// </summary>
        public static string msgbRegisterInvalidNicknameTitle {
            get {
                return ResourceManager.GetString("msgbRegisterInvalidNicknameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas ingresadas no coinciden, modifique los campos para que lo hagan.
        /// </summary>
        public static string msgbRegisterMismatchPasswordMessage {
            get {
                return ResourceManager.GetString("msgbRegisterMismatchPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseñas no coincidentes.
        /// </summary>
        public static string msgbRegisterMismatchPasswordTitle {
            get {
                return ResourceManager.GetString("msgbRegisterMismatchPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe una cuenta registrada con ese correo electrónico, intente con otro.
        /// </summary>
        public static string msgbRegisterRegisteredEmailMessage {
            get {
                return ResourceManager.GetString("msgbRegisterRegisteredEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico registrado.
        /// </summary>
        public static string msgbRegisterRegisteredEmailTitle {
            get {
                return ResourceManager.GetString("msgbRegisterRegisteredEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe otro jugador utilizando el nombre de usuario ingresado, intente con otro.
        /// </summary>
        public static string msgbRegisterRegisteredNicknameMessage {
            get {
                return ResourceManager.GetString("msgbRegisterRegisteredNicknameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario registrado.
        /// </summary>
        public static string msgbRegisterRegisteredNicknameTitle {
            get {
                return ResourceManager.GetString("msgbRegisterRegisteredNicknameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al guardar el reporte. Por favor, intentélo de nuevo más tarde.
        /// </summary>
        public static string msgbReportErrorUpdateMessage {
            get {
                return ResourceManager.GetString("msgbReportErrorUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al guardar.
        /// </summary>
        public static string msgbReportErrorUpdateTitle {
            get {
                return ResourceManager.GetString("msgbReportErrorUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un Error, no se encontró al usuario oponente, intente de nuevo.
        /// </summary>
        public static string msgbReportUserNotFoundMessage {
            get {
                return ResourceManager.GetString("msgbReportUserNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oponente no encontrado.
        /// </summary>
        public static string msgbReportUserNotFoundTitle {
            get {
                return ResourceManager.GetString("msgbReportUserNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La partida a la que intenta enviar el mensaje ya no existe.
        /// </summary>
        public static string msgbSendMessageMatchFinishedMessage {
            get {
                return ResourceManager.GetString("msgbSendMessageMatchFinishedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debido a los reportes recibidos por parte de otros jugadores, su cuenta ha sido bloqueada temporalmente .
        /// </summary>
        public static string msgbTemporalBanGenericMessage {
            get {
                return ResourceManager.GetString("msgbTemporalBanGenericMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debido a los reportes recibidos por parte de otros jugadores, su cuenta ha sido bloqueada temporalmente hasta la fecha: .
        /// </summary>
        public static string msgbTemporalBanMessage {
            get {
                return ResourceManager.GetString("msgbTemporalBanMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta bloqueada temporalmente.
        /// </summary>
        public static string msgbTemporalBanTitle {
            get {
                return ResourceManager.GetString("msgbTemporalBanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido/a .
        /// </summary>
        public static string msgbWelcome1 {
            get {
                return ResourceManager.GetString("msgbWelcome1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  a Adivina Quién.
        /// </summary>
        public static string msgbWelcome2 {
            get {
                return ResourceManager.GetString("msgbWelcome2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código introducido no coincide con el código generado.
        /// </summary>
        public static string msgbWrongConfirmationCodeMessage {
            get {
                return ResourceManager.GetString("msgbWrongConfirmationCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verifique el código ingresado.
        /// </summary>
        public static string msgbWrongConfirmationCodeTitle {
            get {
                return ResourceManager.GetString("msgbWrongConfirmationCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CÓDIGO.
        /// </summary>
        public static string tbCodePlaceholder {
            get {
                return ResourceManager.GetString("tbCodePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Explica la situación.
        /// </summary>
        public static string tbReportCommentPlaceholder {
            get {
                return ResourceManager.GetString("tbReportCommentPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escribe un mensaje….
        /// </summary>
        public static string tbSendMessagePlaceholder {
            get {
                return ResourceManager.GetString("tbSendMessagePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este usuario ya es tu amigo.
        /// </summary>
        public static string txtAlreadyFriends {
            get {
                return ResourceManager.GetString("txtAlreadyFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud de amigo ya existente.
        /// </summary>
        public static string txtAlreadyRequested {
            get {
                return ResourceManager.GetString("txtAlreadyRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu código de confirmación.
        /// </summary>
        public static string txtConfirmationEmailBody {
            get {
                return ResourceManager.GetString("txtConfirmationEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmación de correo electrónico.
        /// </summary>
        public static string txtConfirmationEmailSubject {
            get {
                return ResourceManager.GetString("txtConfirmationEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre completo es requerido para cambiarlo.
        /// </summary>
        public static string txtEmptyFieldFullNameMessage {
            get {
                return ResourceManager.GetString("txtEmptyFieldFullNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campo Nombre vacío.
        /// </summary>
        public static string txtEmptyFieldFullNameTitle {
            get {
                return ResourceManager.GetString("txtEmptyFieldFullNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nuevo nombre de usuario es requerido para cambiarlo.
        /// </summary>
        public static string txtEmptyFieldNicknameMessage {
            get {
                return ResourceManager.GetString("txtEmptyFieldNicknameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campo nombre de usuario vacío.
        /// </summary>
        public static string txtEmptyFieldNicknameTitle {
            get {
                return ResourceManager.GetString("txtEmptyFieldNicknameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitudes.
        /// </summary>
        public static string txtFriendRequests {
            get {
                return ResourceManager.GetString("txtFriendRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amigos.
        /// </summary>
        public static string txtFriends {
            get {
                return ResourceManager.GetString("txtFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha cambiado su nombre en el perfil correctamente.
        /// </summary>
        public static string txtFullNameChangeSuccesfulMessage {
            get {
                return ResourceManager.GetString("txtFullNameChangeSuccesfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre actualizado.
        /// </summary>
        public static string txtFullNameChangeSuccesfulTitle {
            get {
                return ResourceManager.GetString("txtFullNameChangeSuccesfulTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitado.
        /// </summary>
        public static string txtGuest {
            get {
                return ResourceManager.GetString("txtGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anfitrión.
        /// </summary>
        public static string txtHost {
            get {
                return ResourceManager.GetString("txtHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Te han invitado a jugar una partida de Adivina Quién, él código de invitación es:.
        /// </summary>
        public static string txtInviteToGameBody {
            get {
                return ResourceManager.GetString("txtInviteToGameBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Ven a jugar!.
        /// </summary>
        public static string txtInviteToGameSubject {
            get {
                return ResourceManager.GetString("txtInviteToGameSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marcador.
        /// </summary>
        public static string txtLeaderboardGlobal {
            get {
                return ResourceManager.GetString("txtLeaderboardGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        public static string txtLoginGlobal {
            get {
                return ResourceManager.GetString("txtLoginGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú Principal.
        /// </summary>
        public static string txtMainMenuTitle {
            get {
                return ResourceManager.GetString("txtMainMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario cambiado correctamente! Recuerda que no podrás cambiarlo hasta dentro de 3 meses.
        /// </summary>
        public static string txtNicknameChangedSuccesfulMessage {
            get {
                return ResourceManager.GetString("txtNicknameChangedSuccesfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario cambiado.
        /// </summary>
        public static string txtNicknameChangedSuccesfulTitle {
            get {
                return ResourceManager.GetString("txtNicknameChangedSuccesfulTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede cambiar el nombre de usuario en este momento. Debes esperar al menos 3 meses desde el último cambio.
        /// </summary>
        public static string txtNicknameChangeOutOfDateMessage {
            get {
                return ResourceManager.GetString("txtNicknameChangeOutOfDateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio de nombre de usuario no disponible.
        /// </summary>
        public static string txtNicknameChangeOutOfDateTitle {
            get {
                return ResourceManager.GetString("txtNicknameChangeOutOfDateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario.
        /// </summary>
        public static string txtNicknameGlobal {
            get {
                return ResourceManager.GetString("txtNicknameGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa un nombre de usuario que no sea el tuyo.
        /// </summary>
        public static string txtOwnNickname {
            get {
                return ResourceManager.GetString("txtOwnNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña ha sido cambiada correctamente.
        /// </summary>
        public static string txtPasswordChangeSuccesfulMessage {
            get {
                return ResourceManager.GetString("txtPasswordChangeSuccesfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña actualizada.
        /// </summary>
        public static string txtPasswordChangeSuccesfulTitle {
            get {
                return ResourceManager.GetString("txtPasswordChangeSuccesfulTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha cambiado la imagen de perfil correctamente.
        /// </summary>
        public static string txtProfileImageChangeSuccesfulMessage {
            get {
                return ResourceManager.GetString("txtProfileImageChangeSuccesfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen de perfil actualizada.
        /// </summary>
        public static string txtProfileImageChangeSuccesfulTitle {
            get {
                return ResourceManager.GetString("txtProfileImageChangeSuccesfulTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportar.
        /// </summary>
        public static string txtReportGlobal {
            get {
                return ResourceManager.GetString("txtReportGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportar jugador.
        /// </summary>
        public static string txtReportPlayer {
            get {
                return ResourceManager.GetString("txtReportPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya se encuentra registrado con este nombre. Verifique la información e intente de nuevo.
        /// </summary>
        public static string txtSameFullNameErrorMessage {
            get {
                return ResourceManager.GetString("txtSameFullNameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mismo nombre completo.
        /// </summary>
        public static string txtSameFullNameErrorTitle {
            get {
                return ResourceManager.GetString("txtSameFullNameErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya cuentas con este nombre de usuario, ingresa otro e intenta de nuevo.
        /// </summary>
        public static string txtSameNicknameErrorMessage {
            get {
                return ResourceManager.GetString("txtSameNicknameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mismo nombre de usuario.
        /// </summary>
        public static string txtSameNicknameErrorTitle {
            get {
                return ResourceManager.GetString("txtSameNicknameErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu nueva contraseña debe ser distinta a la actual. Verifica la información e intenta de nuevo.
        /// </summary>
        public static string txtSamePasswordChangeErrorMessage {
            get {
                return ResourceManager.GetString("txtSamePasswordChangeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña igual a la actual.
        /// </summary>
        public static string txtSamePasswordChangeErrorTitle {
            get {
                return ResourceManager.GetString("txtSamePasswordChangeErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regístrate.
        /// </summary>
        public static string txtSignUpGlobal {
            get {
                return ResourceManager.GetString("txtSignUpGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error de conexión y la aplicación no pudo completar la solicitud, intente más tarde..
        /// </summary>
        public static string txtSQLErrorMessage {
            get {
                return ResourceManager.GetString("txtSQLErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de conexión.
        /// </summary>
        public static string txtSQLErrorTitle {
            get {
                return ResourceManager.GetString("txtSQLErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La aplicación no logó completar la solicitud, por favor reporte el error e intente más tarde..
        /// </summary>
        public static string txtUpdateErrorMessage {
            get {
                return ResourceManager.GetString("txtUpdateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de actualización.
        /// </summary>
        public static string txtUpdateErrorTitle {
            get {
                return ResourceManager.GetString("txtUpdateErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La aplicación no logró completar la solicitud debido a un error en el formato de los datos, por favor reporte el error..
        /// </summary>
        public static string txtValidationErrorMessage {
            get {
                return ResourceManager.GetString("txtValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos inválidos.
        /// </summary>
        public static string txtValidationErrorTitle {
            get {
                return ResourceManager.GetString("txtValidationErrorTitle", resourceCulture);
            }
        }
    }
}
